package dev.pyetro.desafioanotaai.domain.category.exception;

public class CategoryNotFoundException extends RuntimeException {
}
